# 主配置文件
spring:
  application:
    name: draw2draw-backend
  profiles:
    # 默认激活开发环境配置
    active: dev
  # 通用配置，所有环境共享
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/d2d
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # Session 配置
  session:
    store-type: redis
    timeout: 2592000
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8090
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 开启下划线转驼峰命名
    map-underscore-to-camel-case: false
    # 开启打印 SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 指定mapper xml文件的位置
  mapper-locations: classpath*:generator/mapper/*.xml

knife4j:
  enable: true
  openapi:
    title: Draw2Draw接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xm.draw2drawbackend.controller
